services:
  - type: web
    name: taxis-django-channels
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "daphne -b 0.0.0.0 -p $PORT taxi_project.asgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: taxi_project.settings
      - key: REDIS_URL
        value:  value: "redis://default:AXvhAAIjcDEzMmZmMGExYmI2NDI0MzIyYWNjYmQyZmQwMmRlMmU0N3AxMA@intense-walrus-31713.upstash.io.upstash.io:6379"


